# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1792b2cf3b322c8d84305f2340c74a014185b919b765dc37cb03a3becbe870caf9d486bc6d6806cab92127908ab0dfa431b2885f1993a17ae4212c7298465f3

test:
  secret_key_base: 298ebf75fa1a5a332de72552ef4bfa23603f7a611c9495862302aa4d1efa826ffcd4733f24a9571d4cc43ffcc4c16028fce469bdffc333958744cd54c4e2ca1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
